### ISSUE TITLE
Create a docker image with Open-COBOL-ESQL-4j installed

### ISSUE THREAD

**Issue by ytr-sakamoto** [opensourcecobol/Open-COBOL-ESQL-4j#7]

**Comment by yutaro-sakamoto** [comment]
Open COBOL ESQL 4J is installed in the docker image [opensourcecobol/opensourcecobol4j:1.0.14](https://hub.docker.com/layers/opensourcecobol/opensourcecobol4j/1.0.14/images/sha256-86b29c5c0e8467f191b2cbc77562100888393f0bb0c726363b982476e9aacfca?context=explore) or later versions.
